/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.Appointment;
import dao.AppointmentDAO;
import java.awt.Color;
import java.awt.Font;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class DisplayDoctor extends javax.swing.JFrame {

    /**
     * Creates new form DisplayDoctor
     */
    public DisplayDoctor() {
        initComponents();
        
        setLocation(220, 50);

        Table1.getTableHeader().setFont(new Font("Times New Roman", Font.BOLD, 14));
        Table1.getColumnModel().getColumn(0).setPreferredWidth(120);
        Table1.getColumnModel().getColumn(3).setPreferredWidth(100);
        Table1.getColumnModel().getColumn(5).setPreferredWidth(100);
        Table1.getColumnModel().getColumn(6).setPreferredWidth(105);
        Table1.getColumnModel().getColumn(7).setPreferredWidth(105);

        displayAppointment();
    }

    public void displayAppointment() {

        try {

            AppointmentDAO dao = new AppointmentDAO();
            ResultSet rs = dao.getAllAppointments();
            DefaultTableModel model = (DefaultTableModel) Table1.getModel();
            model.setRowCount(0);

            while (rs.next()) {

                model.addRow(new Object[]{
                    rs.getInt("AppointmentNo"),
                    rs.getString("PatientName"),
                    rs.getString("Address"),
                    rs.getString("ContactNo"),
                    rs.getString("DentistName"),
                    rs.getString("TreatmentType"),
                    rs.getDate("AppointmentDate"),
                    rs.getString("AppointmentTime"),});

            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField = new javax.swing.JTextField();
        Viewbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Logoutbtn = new javax.swing.JButton();
        Searchbtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        Viewbtn2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jTextField.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        Viewbtn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Viewbtn.setText("View");
        Viewbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ViewbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ViewbtnMouseExited(evt);
            }
        });
        Viewbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewbtnActionPerformed(evt);
            }
        });

        Table1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Appointment Number", "Patient Name", "Address", "Contact Number", "Dentist Name", "Treatment Type", "Appointment Date", "Appointment Time"
            }
        ));
        Table1.setGridColor(new java.awt.Color(204, 204, 204));
        Table1.setSelectionBackground(new java.awt.Color(255, 102, 102));
        jScrollPane1.setViewportView(Table1);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Patient Appointment Details");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Welcome, Dentist");

        Logoutbtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Logoutbtn.setText("Logout");
        Logoutbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LogoutbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogoutbtnMouseExited(evt);
            }
        });
        Logoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutbtnActionPerformed(evt);
            }
        });

        Searchbtn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Searchbtn.setText("Search");
        Searchbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SearchbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SearchbtnMouseExited(evt);
            }
        });
        Searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchbtnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Select Treatment Type");

        jComboBox1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Root Canal", "Tooth Extraction", "Dental Implants", "Cleaning", "Whitening" }));

        Viewbtn2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Viewbtn2.setText("Update");
        Viewbtn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Viewbtn2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Viewbtn2MouseExited(evt);
            }
        });
        Viewbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Viewbtn2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82)
                        .addComponent(jLabel2)
                        .addGap(37, 37, 37)
                        .addComponent(Logoutbtn)
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(Searchbtn)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(Viewbtn))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 990, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(79, 79, 79)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(Viewbtn2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(Logoutbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Searchbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76)
                .addComponent(Viewbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(Viewbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ViewbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewbtnMouseEntered
        // TODO add your handling code here:
        Viewbtn.setBackground(Color.green);
    }//GEN-LAST:event_ViewbtnMouseEntered

    private void ViewbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewbtnMouseExited
        // TODO add your handling code here:
        Viewbtn.setBackground(Color.white);
    }//GEN-LAST:event_ViewbtnMouseExited

    private void ViewbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewbtnActionPerformed
        // TODO add your handling code here:
        displayAppointment();
    }//GEN-LAST:event_ViewbtnActionPerformed

    private void LogoutbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutbtnMouseEntered
        // TODO add your handling code here:
        Logoutbtn.setBackground(Color.RED);
    }//GEN-LAST:event_LogoutbtnMouseEntered

    private void LogoutbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutbtnMouseExited
        // TODO add your handling code here:
        Logoutbtn.setBackground(Color.WHITE);
    }//GEN-LAST:event_LogoutbtnMouseExited

    private void LogoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutbtnActionPerformed
        // TODO add your handling code here:
        int Option = JOptionPane.showConfirmDialog(this, "Logout Sunrise Dental Clinic?", "Logout Confirmation", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (Option == JOptionPane.YES_OPTION) {
            LoginForm login = new LoginForm();
            login.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_LogoutbtnActionPerformed

    private void SearchbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchbtnMouseEntered
        // TODO add your handling code here:
        Searchbtn.setBackground(Color.green);
    }//GEN-LAST:event_SearchbtnMouseEntered

    private void SearchbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchbtnMouseExited
        // TODO add your handling code here:
        Searchbtn.setBackground(Color.white);
    }//GEN-LAST:event_SearchbtnMouseExited

    private void SearchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchbtnActionPerformed
        // TODO add your handling code here:

        try {
            String DentistName = jTextField.getText().trim();

            if (DentistName.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Enter Dentist Name");
                return;
            }

            AppointmentDAO dao = new AppointmentDAO();

            ResultSet rs = dao.searchDentistName(DentistName);

            DefaultTableModel model
                    = (DefaultTableModel) Table1.getModel();

            model.setRowCount(0);

            boolean found = false;

            while (rs.next()) {

                found = true;

                model.addRow(new Object[]{
                    rs.getInt("AppointmentNo"),
                    rs.getString("PatientName"),
                    rs.getString("Address"),
                    rs.getString("ContactNo"),
                    rs.getString("DentistName"),
                    rs.getString("TreatmentType"),
                    rs.getDate("AppointmentDate"),
                    rs.getString("AppointmentTime")
                });
            }

            if (!found) {
                JOptionPane.showMessageDialog(
                        this,
                        "No Appointments Found"
                );
            }

        } catch (Exception e) {

            JOptionPane.showMessageDialog(
                    this,
                    "Error: " + e.getMessage()
            );

            e.printStackTrace();
        }
    }//GEN-LAST:event_SearchbtnActionPerformed

    private void Viewbtn2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Viewbtn2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Viewbtn2MouseEntered

    private void Viewbtn2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Viewbtn2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Viewbtn2MouseExited

    private void Viewbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Viewbtn2ActionPerformed
        // TODO add your handling code here:
        int SelectedRow = Table1.getSelectedRow();

        if (SelectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Select an appointment");
        
        return;
    }
    int AppointmentNo = Integer.parseInt(Table1.getValueAt(SelectedRow, 0).toString());

    String TreatmentType = jComboBox1.getSelectedItem().toString();

    
        try{
    AppointmentDAO dao = new AppointmentDAO();
        boolean Updated = dao.UpdateTreatment(AppointmentNo, TreatmentType);

        if (Updated) {
            Appointment a = dao.getAppoitmentByNo(AppointmentNo);
            if (a != null){
                dao.SaveToFile(a);
            }
            JOptionPane.showMessageDialog(this, "Treatment Type Updated");
            displayAppointment();
        }else {
            JOptionPane.showMessageDialog(this, "Update Failed");
        }
} catch (Exception e){
    JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
}
    }//GEN-LAST:event_Viewbtn2ActionPerformed

    /**
         * @param args the command line arguments
         */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DisplayDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DisplayDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DisplayDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DisplayDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DisplayDoctor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Logoutbtn;
    private javax.swing.JButton Searchbtn;
    private javax.swing.JTable Table1;
    private javax.swing.JButton Viewbtn;
    private javax.swing.JButton Viewbtn2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField;
    // End of variables declaration//GEN-END:variables
}
